package com.wzu.qunawan.dao;

import com.wzu.qunawan.pojo.Commentpicture;
import org.springframework.stereotype.Component;

import java.util.List;

@Component(value = "commentpictureMapper")
public interface CommentpictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentpicture
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentpicture
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int insert(Commentpicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentpicture
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    Commentpicture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentpicture
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    List<Commentpicture> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentpicture
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int updateByPrimaryKey(Commentpicture record);
}