package com.wzu.qunawan.dao;

import com.wzu.qunawan.pojo.Contact;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component(value = "contactMapper")
public interface ContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int insert(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    Contact selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    List<Contact> selectAll(int id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int updateByUserId(@Param("record") Contact record,@Param("id") Integer id);

    List<Contact> selectByOrdersuser(int id);

    int updateByContactId(Contact contact);
    List<Contact>selectByUser(int user);
}