package com.wzu.qunawan.dao;

import com.wzu.qunawan.pojo.Dates;
import org.springframework.stereotype.Component;

import java.util.List;

@Component(value = "datesMapper")
public interface DatesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dates
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dates
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int insert(Dates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dates
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    Dates selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dates
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    List<Dates> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dates
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int updateByPrimaryKey(Dates record);
    List<Dates> selectBySchedule(Integer schedule);
}