package com.wzu.qunawan.dao;

import com.wzu.qunawan.pojo.Detail;
import org.springframework.stereotype.Component;

import java.util.List;

@Component(value = "detailMapper")
public interface DetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int insert(Detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    Detail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    List<Detail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int updateByPrimaryKey(Detail record);

    Detail selectByTrip(Integer trip);
}