package com.wzu.qunawan.dao;

import com.wzu.qunawan.pojo.Price;
import org.springframework.stereotype.Component;

import java.util.List;

@Component(value = "priceMapper")
public interface PriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int insert(Price record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    Price selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    List<Price> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int updateByPrimaryKey(Price record);

    List<Price>selectByTrip(Integer price);
}