package com.wzu.qunawan.dao;

import com.wzu.qunawan.pojo.Schedule;
import org.springframework.stereotype.Component;

import java.util.List;

@Component(value = "scheduleMapper")
public interface ScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int insert(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    Schedule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    List<Schedule> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int updateByPrimaryKey(Schedule record);
}