package com.wzu.qunawan.dao;

import com.wzu.qunawan.pojo.Sequence;
import org.springframework.stereotype.Component;

import java.util.List;

@Component(value = "sequenceMapper")
public interface SequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int insert(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    Sequence selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    List<Sequence> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int updateByPrimaryKey(Sequence record);
}