package com.wzu.qunawan.dao;

import com.wzu.qunawan.pojo.Theme;
import org.springframework.stereotype.Component;

import java.util.List;

@Component(value = "themeMapper")
public interface ThemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int insert(Theme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    Theme selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    List<Theme> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int updateByPrimaryKey(Theme record);

    List<Theme> selectByTrip(int trip);
}