package com.wzu.qunawan.dao;

import com.wzu.qunawan.pojo.Themeontrip;
import org.springframework.stereotype.Component;

import java.util.List;

@Component(value = "themeontripMapper")
public interface ThemeontripMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table themeontrip
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table themeontrip
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int insert(Themeontrip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table themeontrip
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    Themeontrip selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table themeontrip
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    List<Themeontrip> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table themeontrip
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int updateByPrimaryKey(Themeontrip record);
}