package com.wzu.qunawan.dao;

import com.wzu.qunawan.pojo.Traffic;
import org.springframework.stereotype.Component;

import java.util.List;

@Component(value = "trafficMapper")
public interface TrafficMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int insert(Traffic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    Traffic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    List<Traffic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table traffic
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int updateByPrimaryKey(Traffic record);

    Traffic selectByTrip(Integer trip);
}