package com.wzu.qunawan.dao;

import com.wzu.qunawan.pojo.Trippicture;
import org.springframework.stereotype.Component;

import java.util.List;

@Component(value = "trippictureMapper")
public interface TrippictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trippicture
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trippicture
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int insert(Trippicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trippicture
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    Trippicture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trippicture
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    List<Trippicture> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trippicture
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int updateByPrimaryKey(Trippicture record);

    List<Trippicture> selectByTrip(Integer trip);
}