package com.wzu.qunawan.dao;

import com.wzu.qunawan.pojo.Trip;
import com.wzu.qunawan.pojo.Tripshow;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component(value = "tripMapper")
public interface TripMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int insert(Trip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    Trip selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    List<Trip> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip
     *
     * @mbg.generated Mon Jun 17 12:43:51 CST 2019
     */
    int updateByPrimaryKey(Trip record);
    List<Trip> selectAllByHot();
    List<Tripshow>selectAllByPlace(String city);

    List<Tripshow>selectAllByPlaceAndCity(@Param("city") String city);
    List<Tripshow> selectAllByTheme(@Param("theme") String theme);
}